# Generated by Django 3.2.7 on 2021-11-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(default='to erase', max_length=400, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=400, unique=True)),
                ('nutriScore', models.CharField(max_length=1)),
                ('linkToIMG', models.CharField(max_length=300, unique=True)),
                ('linkToURLOFF', models.CharField(max_length=300, unique=True)),
                ('linkToNutriForG', models.CharField(max_length=300, unique=True)),
                ('category', models.ManyToManyField(to='products.Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
