# Generated by Django 3.2.7 on 2021-11-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='to erase', max_length=400, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Nutrimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('link', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Nutriscore Image',
                'verbose_name_plural': 'Nutriscores Images',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('nutriScore', models.CharField(max_length=1)),
                ('linkToIMG', models.CharField(max_length=300)),
                ('linkToURLOFF', models.CharField(max_length=300)),
                ('linkToNutriForG', models.CharField(max_length=300)),
                ('category', models.ManyToManyField(to='products.Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
