# Generated by Django 3.2.7 on 2021-10-13 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProductsCategory',
        ),
        migrations.DeleteModel(
            name='ProductsShops',
        ),
        migrations.DeleteModel(
            name='Shops',
        ),
        migrations.DeleteModel(
            name='Surrogate',
        ),
    ]
