# Generated by Django 3.2.7 on 2021-12-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="to erase", max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name="nutrimage",
            name="link",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="product",
            name="linkToIMG",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="product",
            name="linkToNutriForG",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="product",
            name="linkToURLOFF",
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=600),
        ),
    ]
