# Generated by Django 3.2.7 on 2021-10-13 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20211013_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('categoryName', models.CharField(default='to erase', max_length=400, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productID', models.BigAutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=400, unique=True)),
                ('nutriScore', models.CharField(max_length=1)),
                ('linkToIMG', models.CharField(max_length=300, unique=True)),
                ('linkToURLOFF', models.CharField(max_length=300, unique=True)),
                ('linkToNutriForG', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Surrogate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surrogate_product', to='products.products')),
                ('substitut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surrogate_surrogate', to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
